### ISSUE TITLE
请添加网盘和视频站的伪装网站

### ISSUE THREAD

**Issue by yzx1208** [hiifeng/v2ray#2]
请添加网盘和视频站的伪装网站，trojanpanel类似的视频伪装网站。

**Comment by hiifeng** [comment]
你的建议很好，我抽空搜集一下。如果你知道合适的伪装站点网址，请发给我，谢谢

**Comment by yzx1208** [comment]
你太客气了，你可以看下 https://github.com/trojanpanel/install-script 他的这个伪装网站采用的调用YouTube上的视频。但是它的回落好像有问题。但是我不喜欢docker的控制方式，且它的配置选项太单一。更加喜欢vasma的订阅生成。

**Comment by hiifeng** [comment]
感谢分享。
