### ISSUE TITLE
希望能够创建hiifeng的telegram团体

### ISSUE THREAD

**Issue by yzx1208** [hiifeng/v2ray#4]
希望能够创建hiifeng的telegram团体

**Comment by hiifeng** [comment]
欢迎加入交流。https://t.me/HiaiFeng

**Comment by yzx1208** [comment]
hiifeng大大，把这个放入readme中，这样大家都能找到。

**Comment by hiifeng** [comment]
[README.md](https://github.com/hiifeng/v2ray#readme)里有。
