### ISSUE TITLE
无法连接服务器

### ISSUE THREAD

**Issue by ProjektMing** [hiifeng/v2ray#7]
客户端log：
app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [dial tcp x.x.x.x:443: i/o timeout] > common/retry: all retry attempts failed.
服务端log：
app/proxyman/inbound: connection ends > proxy/trojan: failed to find the default "alpn" config
客户端和服务器上的v2ray core都更新到最新了
时好时坏，不过坏的时候更多，另外不知道这个该怎么过cdn，如果开了小黄云，脚本就检测不到域名了……

**Comment by hiifeng** [comment]
提供的信息太少，判断不出原因，有事群里聊。
